timetable v2
NITKC22s/bot-main pull request #119
Opened 2023-06-18 07:50 UTC by starkoka

- 時間割機能をDBに移行
- 授業変更/定期テストに対応
- 時間割機能を複数ギルドに対応
- db.jsにupdateOrInsert関数を追加

2023-06-18 07:51 UTC, starkoka commented
まだやらなくておk

2023-06-23 16:40 UTC, starkoka commented
@naotiki @Kou-Ro @NXVZBGBFBEN の中から2人お願いします...!
1116行変更の超大型プルリクでごめんなさい

2023-06-24 02:53 UTC, starkoka commented
- /add-exceptionコマンドで授業変更、及び定期テストを登録できるようになった
 - /comment-timetableコマンドで,授業にコメントを登録できるようになった

2023-06-24 03:07 UTC, Kou-Ro commented on commands/timeTable.js
> +    ActionRowBuilder,} = require('discord.js');
一行にするか複数行にするかにして

2023-06-24 03:19 UTC, Kou-Ro commented on commands/timeTable.js
> +                const guildData = await db.find("main","guildData",{guild:String(interaction.guildId)});
なんでここStringに変換してるの？
デフォルトでStringじゃね

2023-06-24 03:27 UTC, Kou-Ro commented on commands/timeTable.js
> +                await interaction.editReply("あなたが学科ロールを付けていないか、このサーバーに学科ロールが登録されていないため、学科オプションを省略できません。\nサーバーでロールを付与してもらうか、管理者に伝えてguilddataコマンドで学科ロールを登録してもらってください。");
俺の方だと、/guilddataみたいにスラッシュコマンドの前に/挿入してたんだけど/入れるか入れないかで統一したほうがいいと思うので要検討

2023-06-24 03:27 UTC, Kou-Ro commented on commands/timeTable.js
> +                await interaction.editReply("このサーバーに学年情報が登録されていないため、学年オプションを省略できません。\n管理者に伝えて、guilddataコマンドで入学した年を登録してもらってください。");
同じく

2023-06-24 06:19 UTC, NXVZBGBFBEN commented
あとでやります()

2023-06-24 07:00 UTC, Kou-Ro commented on functions/ttGeneration.js
> + * @returns Embed(存在しない場合0、エラーの場合は-1)
returnsは正確に方の名前を記述する。
自動生成されたもの推奨
これだとIDEに同期処理の関数だと認識される可能性あり。
また、コメントの前に半角スペース入れて

2023-06-24 07:03 UTC, Kou-Ro commented
docコメントのreturnsを削除しないで
基本的には自動生成されたままのやつにコメント追加する形で
意味なくなるし、何なら逆効果になる(余計にIDEに怒られる)

2023-06-24 07:08 UTC, Kou-Ro commented
基本的に同期処理なら必ずPromiseオブジェクトが返るはずなんで、docコメントのreturnsの部分は必ず{Promice<型名>}になるはず

2023-06-24 07:13 UTC, Kou-Ro commented on functions/db.js
> + * @returns bool
returnsの修正

2023-06-24 07:13 UTC, Kou-Ro commented on functions/db.js
>   * @returns Array型
ここ

2023-06-24 07:13 UTC, Kou-Ro commented on functions/db.js
>   */
ここ

2023-06-24 07:13 UTC, Kou-Ro commented on functions/db.js
>  exports.insert = async function run(dbName, collectionName, object) {
この上のとこ

2023-06-24 07:13 UTC, Kou-Ro commented on functions/db.js
> + */
ここ

2023-06-24 07:13 UTC, Kou-Ro commented on functions/db.js
>  exports.delete = async function run(dbName,collectionName,filter) {
この上

2023-06-24 07:13 UTC, Kou-Ro commented on functions/ttGeneration.js
> + */
ここ

2023-06-24 07:13 UTC, Kou-Ro commented on functions/ttGeneration.js
> + */
ここ

2023-06-24 08:24 UTC, Kou-Ro commented on functions/ttGeneration.js
> +    let data = await db.find("main","timetableData",{day:date + '00'});
ここ多分constでも問題ない気がする

2023-06-24 08:24 UTC, NXVZBGBFBEN requested changes
第1弾

2023-06-24 08:25 UTC, Kou-Ro commented on functions/ttGeneration.js
> +            let inputTxt = [],comment;
ここもconstでいける,,,気がする

2023-06-24 08:30 UTC, Kou-Ro requested changes
コメント参照

2023-06-24 08:35 UTC, starkoka commented on commands/timeTable.js
> +                await interaction.editReply("あなたが学科ロールを付けていないか、このサーバーに学科ロールが登録されていないため、学科オプションを省略できません。\nサーバーでロールを付与してもらうか、管理者に伝えてguilddataコマンドで学科ロールを登録してもらってください。");
スラッシュ入れよう

2023-06-24 08:39 UTC, NXVZBGBFBEN commented on commands/timeTable.js
なんか+マークが出てこないので
37行目
(格)助詞抜けの可能性
指定なければ→指定がなければ

2023-06-24 08:57 UTC, NXVZBGBFBEN requested changes

2023-06-24 08:57 UTC, NXVZBGBFBEN commented on commands/timeTable.js
+ ``setDescription``内の句読点を統一すべき
+ 曜日指定の部分に(格)助詞抜けの可能性（指定なければ→指定がなければ）

2023-06-24 09:10 UTC, starkoka commented on functions/ttGeneration.js
> +    let data = await db.find("main","timetableData",{day:date + '00'});
letじゃダメですか?

2023-06-24 09:48 UTC, NXVZBGBFBEN requested changes

2023-06-24 09:48 UTC, NXVZBGBFBEN commented on commands/timeTable.js
>  ]
謎の空行定期

2023-06-24 09:56 UTC, NXVZBGBFBEN commented on botmain.js
> +const { Client, GatewayIntentBits, Partials, Collection, EmbedBuilder,  Events,ActionRowBuilder,StringSelectMenuBuilder} = require('discord.js');
``EmbedBuilder``使ってる？

2023-06-24 11:02 UTC, NXVZBGBFBEN requested changes

2023-06-24 11:02 UTC, NXVZBGBFBEN commented on functions/ttGeneration.js
> +                });
例外から逃げるなァァァァァァ！！！！！！！(言いたいだけ)
あと``error``は使われないので``()``で代用できそうだけどいかが？

2023-06-24 11:02 UTC, NXVZBGBFBEN commented on functions/ttGeneration.js
> +            let replyOptions=time=>{return{content: '登録しました。\n(このメッセージは'+time+'秒後に自動で削除されます)', ephemeral:true};};
``const``にできそう

2023-06-24 11:02 UTC, NXVZBGBFBEN commented on functions/ttGeneration.js
> +        })
``error``を``()``に置き換えたほうがほんの少し見やすくなるかも

2023-06-24 15:13 UTC, starkoka commented on commands/timeTable.js
> +                    subjects += `${2*i+1}-${2*i+2}限：` + defaultData[0].timetable[i].name + '\n';
ホントだwwwなんでだwww

2023-06-24 15:21 UTC, starkoka commented on commands/timeTable.js
> +                    let inputTxt = [],comment;
それは無理っす

2023-06-24 15:22 UTC, starkoka commented on commands/timeTable.js
> +                    let inputTxt = [],comment;
こうやればよかったんだ！

2023-06-24 15:23 UTC, NXVZBGBFBEN commented on commands/timeTable.js
> +                    let inputTxt = [],comment;
AC

2023-06-24 15:27 UTC, starkoka commented on functions/ttGeneration.js
> +    data[0].timetable[parseInt(period)] = {name:interaction.values[0],comment:""};
そうしましょう、FireFoxは8進数になっちゃうからね

2023-06-24 15:50 UTC, Kou-Ro approved these changes

2023-06-24 15:59 UTC, naotiki approved these changes

2023-06-24 16:01 UTC, NXVZBGBFBEN approved these changes
```
[..         [....   [... [......[..       [..
[..       [.    [..      [..    [. [..   [...
[..      [..             [..    [.. [.. [ [..
[..      [..             [..    [..  [..  [..
[..      [..   [....     [..    [..   [.  [..
[..       [..    [.      [..    [..       [..
[........  [.....        [..    [..       [..
                                             
```

2023-06-24 16:05 UTC, merged